name: scopa_service
description: An absolute bare-bones web app.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  uuid: ^4.3.3
  web_socket_channel: ^2.4.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
  test: ^1.21.0
